const products = [
  {
    name: "Handmade Frozen Chicken",
    price: "751.00",
    category: "Donskoy",
    rating: 72,
    id: "1",
  },
  {
    name: "Incredible Bronze Chips",
    price: "615.00",
    category: "Siamese",
    rating: 82,
    id: "2",
  },
  {
    name: "Luxurious Wooden Shirt",
    price: "324.00",
    category: "Singapura",
    rating: 31,
    id: "3",
  },
  {
    name: "Intelligent Bronze Cheese",
    price: "841.00",
    category: "Ojos Azules",
    rating: 89,
    id: "4",
  },
  {
    name: "Intelligent Bronze Chair",
    price: "413.00",
    category: "Thai",
    rating: 94,
    id: "5",
  },
  {
    name: "Gorgeous Plastic Gloves",
    price: "522.00",
    category: "Pixiebob",
    rating: 56,
    id: "6",
  },
  {
    name: "Modern Rubber Bacon",
    price: "131.00",
    category: "Abyssinian",
    rating: 27,
    id: "7",
  },
  {
    name: "Elegant Cotton Chips",
    price: "851.00",
    category: "Singapura",
    rating: 5,
    id: "8",
  },
  {
    name: "Incredible Steel Cheese",
    price: "95.00",
    category: "Turkish Angora",
    rating: 83,
    id: "9",
  },
  {
    name: "Fantastic Granite Ball",
    price: "627.00",
    category: "Egyptian Mau",
    rating: 5,
    id: "10",
  },
  {
    name: "Bespoke Fresh Table",
    price: "586.00",
    category: "Ocicat",
    rating: 90,
    id: "11",
  },
  {
    name: "Intelligent Plastic Fish",
    price: "295.00",
    category: "Kurilian Bobtail",
    rating: 72,
    id: "12",
  },
  {
    name: "Elegant Fresh Table",
    price: "17.00",
    category: "British Shorthair",
    rating: 76,
    id: "13",
  },
  {
    name: "Fantastic Fresh Salad",
    price: "614.00",
    category: "Turkish Angora",
    rating: 12,
    id: "14",
  },
  {
    name: "Refined Bronze Car",
    price: "560.00",
    category: "Kurilian Bobtail",
    rating: 33,
    id: "15",
  },
  {
    name: "Refined Granite Chicken",
    price: "543.00",
    category: "Abyssinian",
    rating: 73,
    id: "16",
  },
  {
    name: "Intelligent Bronze Bike",
    price: "606.00",
    category: "Highlander",
    rating: 9,
    id: "17",
  },
  {
    name: "Handcrafted Bronze Pizza",
    price: "463.00",
    category: "Scottish Fold",
    rating: 43,
    id: "18",
  },
  {
    name: "Practical Steel Bacon",
    price: "848.00",
    category: "Bengal",
    rating: 58,
    id: "19",
  },
  {
    name: "Practical Steel Table",
    price: "945.00",
    category: "Bombay",
    rating: 40,
    id: "20",
  },
  {
    name: "Modern Soft Pants",
    price: "667.00",
    category: "Siamese",
    rating: 75,
    id: "21",
  },
  {
    name: "Incredible Frozen Soap",
    price: "427.00",
    category: "Ragdoll",
    rating: 43,
    id: "22",
  },
  {
    name: "Elegant Steel Bacon",
    price: "815.00",
    category: "Toyger",
    rating: 37,
    id: "23",
  },
  {
    name: "Bespoke Frozen Car",
    price: "731.00",
    category: "Turkish Angora",
    rating: 13,
    id: "24",
  },
  {
    name: "Handmade Rubber Salad",
    price: "694.00",
    category: "Nebelung",
    rating: 27,
    id: "25",
  },
  {
    name: "Bespoke Bronze Car",
    price: "802.00",
    category: "American Bobtail",
    rating: 32,
    id: "26",
  },
  {
    name: "Refined Frozen Tuna",
    price: "815.00",
    category: "Devon Rex",
    rating: 23,
    id: "27",
  },
  {
    name: "Awesome Plastic Bike",
    price: "299.00",
    category: "American Bobtail",
    rating: 51,
    id: "28",
  },
  {
    name: "Electronic Fresh Pizza",
    price: "134.00",
    category: "American Bobtail",
    rating: 86,
    id: "29",
  },
  {
    name: "Rustic Granite Ball",
    price: "43.00",
    category: "Sphynx",
    rating: 22,
    id: "30",
  },
  {
    name: "Handmade Steel Pizza",
    price: "312.00",
    category: "American Curl",
    rating: 1,
    id: "31",
  },
  {
    name: "Awesome Rubber Chicken",
    price: "452.00",
    category: "Manx",
    rating: 18,
    id: "32",
  },
  {
    name: "Sleek Fresh Keyboard",
    price: "988.00",
    category: "Ragdoll",
    rating: 30,
    id: "33",
  },
  {
    name: "Tasty Granite Pants",
    price: "673.00",
    category: "Devon Rex",
    rating: 70,
    id: "34",
  },
  {
    name: "Tasty Wooden Bike",
    price: "762.00",
    category: "Sphynx",
    rating: 16,
    id: "35",
  },
  {
    name: "Generic Concrete Gloves",
    price: "387.00",
    category: "American Bobtail",
    rating: 90,
    id: "36",
  },
];
